name: mykebun
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  expansion_tile_group: ^2.0.0
  curved_labeled_navigation_bar: ^2.0.2
  flashy_tab_bar2: ^0.0.6
  intl: ^0.18.1
  google_fonts: ^5.1.0
  http: ^1.1.0
  lottie: ^2.6.0
  image_picker: ^0.8.5+3
  flutter_tflite: ^1.0.1
  flutter_neumorphic: ^3.2.0
  url_launcher: ^6.1.12
  quickalert: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie/temperature.json
    - assets/lottie/humidity.json
    - assets/lottie/precipitation.json
    - assets/lottie/soilTemperature.json
    - assets/lottie/soilMoisture.json
    - assets/lottie/uv.json
    - assets/lottie/corn.json
    - assets/lottie/loading.json
    - assets/lottie/loadingNew.json
    - assets/image/corn.png
    - assets/image/chili.png
    - assets/image/cucumber.png
    - assets/image/tomato.png
    - assets/image/pumpkin.png
    - assets/image/bitter-gourd.png
    - assets/image/right-arrow.png
    - assets/image/insignia.png
    - assets/image/ai.png
    - assets/image/brain.png

    - lib/assets/images/picture.png
    - lib/assets/images/shopping-cart.png
    - lib/assets/labels.txt
    - lib/assets/model.tflite
    - lib/assets/images/leaf.png
    - lib/assets/images/chemicals.png
    - lib/assets/images/camera-plant.png
    - lib/assets/images/arrow-down.png
    - lib/assets/images/diagnosis.png
    - lib/assets/images/treatment.png
    - lib/assets/images/one.png
    - lib/assets/images/two.png
    - lib/assets/images/three.png
    - lib/assets/images/farmer.png
    - lib/assets/images/line.png
    - lib/assets/images/trichoderma.jpg
    - lib/assets/images/tebuconazole.png
    - lib/assets/images/bacillus.jpg
    - lib/assets/images/scan.png
    - lib/assets/images/scan-plant.png
    - lib/assets/images/icon-mykebun.png
    - lib/assets/images/icon-mykebun2.png
    - lib/assets/images/tricho.jpg
    - lib/assets/images/bacto.jpg
    - lib/assets/images/neem.jpg
    - lib/assets/images/pestbacillus.jpg
    - lib/assets/images/syngenta.jpg
    - lib/assets/images/silicon.jpg
    - lib/assets/images/parasol.jpg
    - lib/assets/images/header.jpg
    - lib/assets/images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
